# Motivation

The Klein Gorder equation

$$
0 = (\Box +m^2)\psi = (\partial_t^2- \nabla^2 +m^2)\psi = (\partial_t^2 +p^2 +m^2)\psi
$$

Reproduces the Einstein energy equation

$$
E^2 =  p^2 c^2 + m^2 c^4
$$

Because of the negative energy solutions, Dirac looked for an equation linear in time to reproduce

$$
E = \sqrt{p^2 c^2 + m^2 c^4}
$$

One way to go about it is to try to "factor" the Klein Gordon operator

$$
\partial^2 + m^2 = (i\gamma^\mu \partial_\mu - m)(i\gamma^\mu \partial_\mu + m)
$$

Then it must be the case

$$
\{\gamma^\mu, \gamma^\nu\} = 2\eta^{\mu\nu}
$$

The gamma elements form a Clifford algebra. They can be represented with 4x4 matrices. 

$$
\gamma^0 = 
\begin{pmatrix}
I & 0 \\
0 & -I
\end{pmatrix}
= I \otimes \sigma_3
$$
$$
\gamma^i = 
\begin{pmatrix}
0 & \sigma^i \\
-\sigma^i & 0
\end{pmatrix}
= \sigma^i \otimes i \sigma_2
$$

Define 

$$
\gamma^5 = i \gamma^0\gamma^1\gamma^2\gamma^3 = I \otimes \sigma_1
$$

$$
\sigma^{\mu\nu} = \frac{i}{2}[\gamma^\mu,\gamma^\nu]
$$

Then the following matrices form a basis for the complete Clifford algebra (representation)

$$
I, \sigma^{\mu\nu}, \gamma^\mu, \gamma^\mu \gamma^5 , \gamma^5
$$

Furthermore, the $\sigma^{\mu\nu}$ are the generators of the Lorentz Group

$$
S(\Lambda) = e^{-(i/4)\omega_{\mu\nu} \sigma^{\mu\nu}}
$$

Dirac spinors transform under the gamma matrices and can be represented as a pair of Weyl spinors

$$
\psi = \begin{pmatrix}\phi\\ \chi\end{pmatrix}
$$



Multiplying from both sides by $\gamma^0$ produces the Hermitian conjugate

Define
$$
\bar{\psi} := \psi^\dagger \gamma_0
$$

In [1]:
import numpy as np

In [5]:
# Pauli Matrices

PAULI_X = np.matrix([[0, 1], [1, 0]])
PAULI_Y = np.matrix([[0, -1j], [1j, 0]])
PAULI_Z = np.matrix([[1, 0], [0, -1]])

sigma = np.array([np.eye(2), PAULI_X, PAULI_Y, PAULI_Z])

In [7]:
sigma

array([[[ 1.+0.j,  0.+0.j],
        [ 0.+0.j,  1.+0.j]],

       [[ 0.+0.j,  1.+0.j],
        [ 1.+0.j,  0.+0.j]],

       [[ 0.+0.j, -0.-1.j],
        [ 0.+1.j,  0.+0.j]],

       [[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]])

In [9]:
# Define outer product 
def outer(x,y): return np.kron(y,x)

In [72]:
# Example
outer(sigma[0],sigma[3])

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -1.+0.j]])

In [78]:
# Define commutator and anticommutator

def comm(x,y): return x@y - y@x
def acomm(x,y): return x@y + y@x

In [90]:
# Example
comm(sigma[1],sigma[2])

array([[0.+2.j, 0.+0.j],
       [0.+0.j, 0.-2.j]])

In [92]:
acomm(sigma[1],sigma[2])

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [28]:
# Define Gamma matrices

gamma = []
gamma.append(outer(sigma[0], sigma[3]))
for i in range(1,4):
    gamma.append(outer(sigma[i],1j*sigma[2]))


In [30]:
gamma = np.array(gamma)
print(gamma)

[[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  0.+0.j -1.+0.j -0.+0.j]
  [ 0.+0.j  0.+0.j -0.+0.j -1.+0.j]]

 [[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
  [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
  [-0.+0.j -1.+0.j  0.+0.j  0.+0.j]
  [-1.+0.j -0.+0.j  0.+0.j  0.+0.j]]

 [[ 0.+0.j  0.-0.j  0.+0.j -0.-1.j]
  [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]
  [-0.+0.j  0.+1.j  0.+0.j  0.-0.j]
  [-0.-1.j -0.+0.j  0.+0.j  0.+0.j]]

 [[ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
  [ 0.+0.j -0.+0.j  0.+0.j -1.+0.j]
  [-1.+0.j -0.+0.j  0.+0.j  0.+0.j]
  [-0.+0.j  1.-0.j  0.+0.j -0.+0.j]]]


In [32]:
# Define gamma 5
gamma5 = 1j*(gamma[0]@gamma[1]@gamma[2]@gamma[3])
print(gamma5)

[[0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]


## Free Particle Solution

\begin{eqnarray}
\not{p}\psi = m\psi &\implies & (E\gamma^0  - \gamma\cdot p)\psi = m\psi 
&\implies&
\begin{bmatrix}
E-m & \sigma\cdot p\\
-\sigma\cdot p & -(E+m)
\end{bmatrix}
\begin{bmatrix}
\phi\\ \chi
\end{bmatrix}
= 0
\end{eqnarray}

From which we get 
$$
\chi = \frac{\sigma\cdot p}{E+m}\phi
$$

Solving for $\phi$:

$$
(E^2 - m^2 - (\sigma\cdot \mathbf{p})^2)\phi = 0 \implies (E^2 - m^2 - \mathbf{p}^2)\phi = 0
$$

Since $E^2 = m^2 c^4 + \mathbf{p}^2 c^2$, the multiplier is 0, which means $\phi$ spans a 2D subspace.

The complete solution is given by

$$
\begin{cases}
\begin{aligned}
    E > 0: & \quad \Psi^{(1)} = \mathcal{N} \begin{pmatrix}
    1 \\
    0 \\
    \frac{p_z}{E + m} \\
    \frac{p_x + i p_y}{E + m}
    \end{pmatrix} e^{-ip \cdot x}, \quad \Psi^{(2)} = \mathcal{N} \begin{pmatrix}
    0 \\
    1 \\
    \frac{p_x - i p_y}{E + m} \\
    -\frac{p_z}{E + m}
    \end{pmatrix} e^{-ip \cdot x}; \\[10pt]
    E < 0: & \quad \Psi^{(3)} = \mathcal{N} \begin{pmatrix}
    \frac{p_z}{E - m} \\
    \frac{p_x + i p_y}{E - m} \\
    1 \\
    0
    \end{pmatrix} e^{-ip \cdot x}, \quad \Psi^{(4)} = \mathcal{N} \begin{pmatrix}
    \frac{p_x - i p_y}{E - m} \\
    -\frac{p_z}{E - m} \\
    0 \\
    1
    \end{pmatrix} e^{-ip \cdot x}.
\end{aligned}
\end{cases}
$$


Consequences

1. Both positive and negative energy solutions
2. In the non-relativistic limit $p/(E+m) \rightarrow 0$, so the positive energy solution is dominated by top components. The negative by the lower.

### Hamiltonian

$$
i\gamma^0 \partial_t \psi + i\mathbf{\gamma}\cdot\nabla\psi = m\psi \implies
i\partial_y \psi = -i\gamma^0\mathbf{\gamma}\cdot\nabla\psi +  m\gamma^0 \psi 
$$

so $H = i\gamma^0\mathbf{\gamma}\cdot\nabla +m\gamma^0$

The angular momentum $L = p \times x$ does not commute with $H$, so it is not conserved.
It $L+\Sigma$ which is conserved, where $\Sigma = \begin{bmatrix}\sigma & 0\\0 & \sigma \end{bmatrix}$

## Adjoint and Lagrangian

Take the Hermitian conjugate. We are going to use $(\gamma^\mu)^\dagger = \gamma^0\gamma^\mu\gamma^0$.

$$
\psi^\dagger\left((\gamma^\mu)^\dagger)p_\mu-m\right) = 0 \implies 
\psi^\dagger\left(\gamma^0\gamma^\mu\gamma^0 p_\mu-m\right) = 0 
$$

Multiply with $ \gamma^0$ from the right

$$
\psi^\dagger\gamma^0 \left(\gamma^\mu p_\mu-m\right) = 0 \implies \bar{\psi}\left(\gamma^\mu p_\mu-m\right) = 0 
$$

Lagrangian

$$
L = \bar{\psi}(\not{\partial}-m)\psi
$$

Currency Density

$$
\partial_\mu (\bar{\psi}\gamma^\mu\psi) = 0
$$

## Weyl Representation

In this representaton, $\mathbf{\gamma}$ is the same but $\gamma^0 = \begin{bmatrix}0 & I\\I &0\end{bmatrix}$
The equation in this representation reads

$$
\begin{bmatrix}
0 & E-\sigma\cdot p\\ 
E+\sigma\cdot p & 0
\end{bmatrix} 
\begin{bmatrix}
\phi \\ \chi
\end{bmatrix}
=
\begin{bmatrix}
m\phi \\ m\chi
\end{bmatrix}
$$

In the case of $m=0$, the spinor separates into two independent equations.

$$
 (E \pm \sigma\cdot p)\psi_{R/L} = 0
$$

Chirality projectors: $\frac{1}{2}(1 \pm \gamma^5)$

## Problems

### Rubia 8.1

Show that the Dirac gamma matrices satisfy the Clifford Algebra sl(1,3)

#### Solution

$$
\gamma_0^2 = I, \gamma_i^2 = -I
$$

In [69]:
[g@g for g in gamma]

[array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]]),
 array([[-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]]),
 array([[-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]]),
 array([[-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])]

$$
\{\gamma^\mu, \gamma^\nu\} = 2\eta^{\mu\nu}
$$

In [100]:
[acomm(g,g) for g in gamma]

[array([[2.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 2.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 2.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 2.+0.j]]),
 array([[-2.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -2.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -2.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -2.+0.j]]),
 array([[-2.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -2.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -2.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -2.+0.j]]),
 array([[-2.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -2.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -2.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j, -2.+0.j]])]

In [112]:
# Example
acomm(gamma[1],gamma[2])

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

furthermore 

$$
\gamma_0^\dagger = \gamma_0, \gamma_i^\dagger = -\gamma_i
$$

In [117]:
[g.T.conj() for g in gamma]

[array([[ 1.-0.j,  0.-0.j,  0.-0.j,  0.-0.j],
        [ 0.-0.j,  1.-0.j,  0.-0.j,  0.-0.j],
        [ 0.-0.j,  0.-0.j, -1.-0.j, -0.-0.j],
        [ 0.-0.j,  0.-0.j, -0.-0.j, -1.-0.j]]),
 array([[ 0.-0.j,  0.-0.j, -0.-0.j, -1.-0.j],
        [ 0.-0.j,  0.-0.j, -1.-0.j, -0.-0.j],
        [ 0.-0.j,  1.-0.j,  0.-0.j,  0.-0.j],
        [ 1.-0.j,  0.-0.j,  0.-0.j,  0.-0.j]]),
 array([[ 0.-0.j,  0.-0.j, -0.-0.j, -0.+1.j],
        [ 0.+0.j,  0.-0.j,  0.-1.j, -0.-0.j],
        [ 0.-0.j,  0.-1.j,  0.-0.j,  0.-0.j],
        [-0.+1.j,  0.-0.j,  0.+0.j,  0.-0.j]]),
 array([[ 0.-0.j,  0.-0.j, -1.-0.j, -0.-0.j],
        [ 0.-0.j, -0.-0.j, -0.-0.j,  1.+0.j],
        [ 1.-0.j,  0.-0.j,  0.-0.j,  0.-0.j],
        [ 0.-0.j, -1.-0.j,  0.-0.j, -0.-0.j]])]

### Problem

For a 3-vector $(x,y,z)$ show that

$$
\sigma\cdot \bf{x} = \begin{bmatrix}
z & x-iy\\x+iy & -z
\end{bmatrix}
$$

and $(\sigma\cdot x)^2 = |x|^2 I$

### Reading Material

- Rubbia, Phenomenology of Particle Physics, Chapter 8
- Peskin, An Introduction to Quantum Field Theory, Sections 3.1 - 3.4
- Jakob Schwichtenberg , No Nonsense QFT, Sections 3.3 - 3.4
- Eigenchris, Spinors for Beginners: https://www.youtube.com/watch?v=j5soqexrwqY&list=PLJHszsWbB6hoOo_wMb0b6T44KM_ABZtBs