# Susskind - Quantum Mechanics
## Chapters 6 - 7

#### Latex: Define bras, kets, brackets
$
\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}
\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}
$

### Exercise 6.1

$COV(X,Y) = E[XY] - E[X]E[Y]$

If $P(X,Y) = P(X)P(Y)$ then also $E(X,Y) = E(X)E(Y)$, so $COV(X,Y) = 0$


### Exercise 6.2

$$
\sum_i\sum_j |a_i b_j|  = \sum_i\sum_j |a_i||b_j| = \sum_i |a_i|\sum_j |b_j| = 1\cdot 1 = 1
$$

### Exercise 6.3

$$\ket{sing} = \frac{1}{\sqrt{2}}(\ket{ud}-\ket{du})
$$
Show that it cannot be written as a product state

#### Solution
Suppose $\ket{sing} = \ket{a}\ket{b}$

$$
\ket{a}\ket{b}$ = (a_u\ket{u}+a_d\ket{d})(b_u\ket{u}+b_d\ket{d}) = \\
a_u b_u\ket{uu}+a_d b_u\ket{du} + a_d b_u\ket{du}+ a_d b_d\ket{dd}
$$

Then we must have 

$$
a_u b_u = 0 \\
a_d b_d = 0
$$

But then, either $a_d b_u$ or $a_u b_d$ would have to be 0 as well

### Exercise 6.5

Show that in a product state the expectation of any component is the same as it would be for individual states.

#### Solution
This can be shown in general for any operator $O$. I must use the following: 
$\bra{ab} = \bra{b}\otimes \bra{a}$

$$
<O> = \bra{ab}O\otimes I\ket{ab} = \bra{b}⊗ \bra{a}O\otimes I\ket{a}\otimes \ket{b} = \\
\bra{b} \braket{a}{Oa} \ket{b} = <O>\braket{b}{b} = <O>
$$

Note that this only holds for states that can be written as a product. 
The more general result is in section 7.4 

### Exercise 6.6
What is the expectation of $\sigma_x\tau_y$ in $\ket{sing}$?

#### Solution

$$
\sigma_x\tau_y(\ket{ud}-\ket{du}) = -i\ket{du}-i\ket{ud} = -i(\ket{du}+\ket{ud})
$$

$$
so <\sigma_x\tau_y> = \frac{1}{2}(\bra{ud}-\bra{du})(\ket{ud}+\ket{du}) =  \frac{1}{2}(\braket{ud}{ud} - \braket{du}{du}) = 0
$$

### Exercise 6.9

#### Solution

$\ket{T_i}$ all have the same eignevalue 1. $\ket{sing}$ has eignevalue -3

### Exercise 6.10

$$
H = \omega\hbar (\sigma\cdot\tau)
$$
I changed H to make the exponentials easier.


From 6.9 we know 4 eigenvectors of $\sigma\cdot\tau$. The eigenvectors are orthormal. Furthermore, a 4x4 matrix can have at most 4 eigenvectors, so this is the complete set of eigenvectors.

Consequently, the only eignvalues of H are $-3\omega\hbar$ and $\omega\hbar$.

$$
\ket{uu} = \frac{1}{\sqrt{2}}(T_2+T_3) \implies\\
\ket{uu}_t  = \frac{1}{\sqrt{2}}(e^{-i\omega}T_2+e^{-i\omega}T_3) = \frac{e^{-i\omega}}{\sqrt{2}}(T_2+T_3) =\\
\frac{e^{-i\omega}}{2}\ket{uu}
$$

Even though it starts in a state that is not an eigenvector, the expectation stays constant.

$\ket{dd}$ produces a similar result.

$\ket{ud} = \frac{1}{\sqrt{2}}(\ket{sing}+T_1)$ is more interesting

$$
\ket{ud}_t = \frac{1}{\sqrt{2}}(e^{-i\omega}T_1+e^{i3\omega}\ket{sing})
$$

## Chapter 7

In [1]:
import numpy as np

sigma_z = [[1, 0],[0, -1]]
I = [[1,0],[0,1]]

np.kron(sigma_z, I)

array([[ 1,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [2]:
u = [1,0]
d = [0, 1]

np.kron(u,u)

array([1, 0, 0, 0])

In [3]:
np.kron(u,d)

array([0, 1, 0, 0])

In [4]:
# Define Pauli matrices

sigma_x = [[0, 1],[1, 0]]
sigma_y = [[1j, 0], [0,-1j]]

# Define 2-spin states
uu = np.kron(u,u)
ud = np.kron(u,d)
du = np.kron(d,u)
dd = np.kron(d,d)

### Exercise 7.1

In [5]:
operator = np.kron(I, sigma_x)
operator

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [6]:
operator @ uu

array([0, 1, 0, 0])

In [7]:
operator @ dd

array([0, 0, 1, 0])

In [8]:
operator @ ud

array([1, 0, 0, 0])

In [9]:
operator @ du

array([0, 0, 0, 1])

## Exercise 7.2

In [10]:
operator = np.kron(sigma_z, sigma_x)
operator

array([[ 0,  1,  0,  0],
       [ 1,  0,  0,  0],
       [ 0,  0,  0, -1],
       [ 0,  0, -1,  0]])

In [11]:
operator @ uu

array([0, 1, 0, 0])

In [12]:
operator @ dd

array([ 0,  0, -1,  0])

In [13]:
operator @ ud

array([1, 0, 0, 0])

In [14]:
operator @ du

array([ 0,  0,  0, -1])

## Projection Operators

$\ket{\psi}\bra{\psi}$ projects onto the state $\psi$

#### Properties

Let P be a projection operator. Then 

a) P is Hermitean

b) $\ket{\psi}$ is an eigenvector with eigenvalue 1

c) The eigenvalues of P are 0 or 1

d) $P^2 = P$

e) $TrP = 1$

f) If $\ket{i}$ is an orthonormal basis, then $\sum_i\ket{i}\bra{i} = I$


### Proof

a) $P_{ij} = \braket{i}{\psi}\braket{\psi}{j}= \braket{j}{\psi}^* \braket{\psi}{i}^* = 
\left(\braket{j}{\psi} \braket{\psi}{i}\right)^* = P_{ji}^*$

b) $P\ket{\psi} = \ket{\psi}\braket{\psi}{\psi} = \ket{\psi}$

c) Let $\ket{\phi}$ be orthogonal to $\ket{\psi}$. Then

$\ket{\psi}\braket{\psi}{\phi} = 0$, so every orthogonal vector is an eigenvector with eigenvalue 0

d) $P^2 = \ket{\psi}\braket{\psi}{\psi}\bra{\psi} = \ket{\psi}\bra{\psi} = P$

e) $TrP = \sum_i\braket{i}{\psi}\braket{\psi}{i} = \sum_i\braket{i}{\psi}\braket{i}{\psi}^* = \sum_i |\braket{i}{\psi}|^2 = 1$

f) 

Recall, for an orthonormal basis $\ket{i}$ and any vector $\ket{\phi} = \sum_i\ket{i}\braket{i}{\phi}$ (a)

No take the  operator $K = \sum_i\ket{i}\bra{i}$ and apply to $\ket{\phi}$, we get:

$K\ket{\phi} = \sum_i\ket{i}\braket{i}{\phi}$ 

But from (a) we know that $\sum_i\ket{i}\braket{i}{\phi}= \ket{\phi} $.

Therefore $K\ket{\phi} = \ket{\phi}$, which means $K = I$.



## Mixed States

Given a set of states $\ket{\psi_i}$, not necessarily orthogonal, and a (classical) probability distribution $p_i$ 
over the states, the **density matrix** is defined as

$$
\rho = \sum_i p_i \ket{\psi_i}\bra{\psi_i}
$$

A *pure state* is a state of the form $\ket{\psi}\bra{\psi}$ (a projection operator).

#### Properties

a) $\rho$ is Hermitean

b) Trρ = 1

c) The eignevalues are positive and lie between 0 and 1. So, if any eigenvector has eigenvalue 1, the others are 0

d) For a pure state
$$
\rho^2 = \rho\\
Tr\rho^2 = 1
$$

e) For a mixed state

$$
\rho^2 \neq \rho\\
Tr\rho^2 < 1
$$

#### Proof

a) 
$$
\rho_{ij} = \sum_k p_k \braket{i}{\psi_k}\braket{\psi_k}{j} =\\
 \sum_k p_k \braket{j}{\psi_k}^*\braket{\psi_k}{i}^* = \\
 \left(\sum_k p_k \braket{j}{\psi_k}\braket{\psi_k}{i}\right)^* = \rho_{ji}^*
$$

b)

$$
Trρ = \sum_i \bra{i}\rho\ket{i} = \sum_{ik}p_k\braket{i}{\psi_k}\braket{\psi_k}{i} = \\
\sum_{ik}p_k|\braket{i}{\psi_k}|^2 = \sum_k p_k \sum_i |\braket{i}{\psi_k}|^2 = \\
\sum_k p_k = 1
$$

c) Let $\ket{i}$ be an orthonormal 

d) A pure state is just a projection, so we have already proved that.

### Problem 7.4

In [15]:
import sympy as sp

a = sp.Symbol("a", complex = True)
b = sp.Symbol("b", complex = True)
rho = sp.Matrix([[sp.conjugate(a)*a, sp.conjugate(a)*b],[sp.conjugate(b)*a, sp.conjugate(b)*b]])

In [16]:
rho

Matrix([
[a*conjugate(a), b*conjugate(a)],
[a*conjugate(b), b*conjugate(b)]])

In [17]:
rho.subs([(a, 1), (b,0)])

Matrix([
[1, 0],
[0, 0]])

In [23]:
def normalize(v):
    x = v[0]
    y = v[1]
    norm = np.sqrt(x**2+y**2)
    return [x,y]/norm

normalize([1.,1.])

array([0.70710678, 0.70710678])

In [1]:
def plug_in(matrix, values):
    nvalues = normalize(values)
    return matrix.subs([(a, nvalues[0]), (b,nvalues[1])])

In [27]:
plug_in(rho, [1,1])

Matrix([
[0.5, 0.5],
[0.5, 0.5]])

In [28]:
plug_in(rho, [2,1])

Matrix([
[0.8, 0.4],
[0.4, 0.2]])

In [31]:
r = plug_in(rho, [1,1+1j])

In [33]:
sp.simplify(r)

Matrix([
[                      0.447213595499958, 0.447213595499958 + 0.447213595499958*I],
[0.447213595499958 - 0.447213595499958*I,                       0.894427190999916]])

### Problem 7.5

#### Solution

$\rho^2 = 
\begin{bmatrix}
\frac{1}{9} & 0\\
0 & \frac{4}{9}
\end{bmatrix}
$

$Tr(\rho) = 1$

$Tr(\rho^2) = 5/9$

mixed state

### Problem 7.6

$$
Tr(\rho) = \sum_i \rho_{ii} = \sum_i \sum_j \psi^*(i,j)\psi(i,j) = \sum_{ij} |\psi(i,j)|^2 = 1
$$

### Problem 7.7 

#### Solution

$\rho^2 = 
\begin{bmatrix}
\frac{1}{4} & 0\\
0 & \frac{1}{4}
\end{bmatrix}
$

$Trρ < Tr\rho^2$ indicates this is a mixed state. An entagled state must be one of minimal information,
which is achieved when all probabilities are equal.

### Problem 7.8

Compute A and B density matrices for the following states

$$
\ket{\psi_1} = \frac{1}{2}\left(\ket{uu}+\ket{ud}+\ket{du}+\ket{dd} \right)
$$

$$
\ket{\psi_2} = \frac{1}{\sqrt{2}}\left(\ket{uu}+\ket{dd} \right)
$$

$$
\ket{\psi_3} = \frac{1}{5}\left(3\ket{uu}+4\ket{ud} \right)
$$

#### Solution

In the first two cases, A and B densities are the same because exchanging u and d results in the same state (parity!)
The only interesting case is $\psi_3$. 

$\psi(u,u) = 3/5, \psi(u,d) = 4/5$

$\rho_A = 
\begin{bmatrix}
1 & 0\\
0 & 0
\end{bmatrix}
$ 

$\rho_B = 
\begin{bmatrix}
\frac{9}{25} & 0\\
0 & \frac{16}{25}
\end{bmatrix}
$ 

Alice has complete certainty that she will measure $u$ because that's her only option. Bob's results are mixed

### Problem 7.9

The statement here is too wishy washy. The product state cobmines two vector spaces. Furthermore A, and B are operators in two different vector spaces so they cannot be multiplied. 
I suppose the author means to use $A\otimes I$ and  $I\otimes B$ as the operators on the product space. This requires additional care in re-interpreting the product AB.


### Problem 7.10

$$
a_u\ket{u,b}+a_d\ket{d,b} = (a_u\ket{u}+a_d\ket{d})\otimes\ket{b}
$$

so it's a product state