# Quantum Computation and Quantum Information
## Chapter 4 Problems

In [19]:
import numpy as np

I = np.matrix([[1, 0], [0, 1]])
X = np.matrix([[0, 1], [1, 0]])
Y = np.matrix([[0, -1j], [1j, 0]])
Z = np.matrix([[1, 0], [0, -1]])
H = np.matrix([[1, 1], [1, -1]])/np.sqrt(2)
S= np.matrix([[1, 0], [0, 0+1j]])
T = np.matrix([[1, 0], [0, np.exp(1j*np.pi/4)]])

In [17]:
T

matrix([[1.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 0.70710678+0.70710678j]])

### Exercise 4.2

$$
exp(iAx) = \sum_{n=0}^\infty (iAx)^n/n! = 
exp(iAx) = \sum_{n=0}^\infty (iAx)^{2n}/(2n)! + \sum_{n=0}^\infty (iAx)^{2n+1}/(2n+1)! =\\
\sum_{n=0}^\infty (-1)^n I (x)^{2n}/(2n)! + \sum_{n=0}^\infty iA (-1)^n x^{2n+1}/(2n+1)! =\\
I\cos(x) + iA\sin(x)
$$

### Exercise 4.3

$$
T =\begin{bmatrix}
1 & 0\\0 & e^{i\pi/4}
\end{bmatrix} 
= e^{i\pi/8}
\begin{bmatrix}
e^{-i\pi/8} & 0\\0 & e^{i\pi/8}
\end{bmatrix} 
= e^{i\pi/8} R_z(\pi/4)
$$

### Exercise 4.5

$$
(n\cdot \sigma)^2 = \sum_{ij}n_i\sigma_i n_j\sigma_j = \sum_{ij}n_i n_j \delta_{ij}I = 
\sum_i n_i^2 I = I 
$$

### Exercise 4.7

In [4]:
X*Y*X

matrix([[0.+0.j, 0.+1.j],
        [0.-1.j, 0.+0.j]])

The result also follows directly from the fact that the Pauli matrices anti-commute and have square I.

Now we can use $R_y(\theta) = I\cos(\theta/2) - iY\sin(\theta/2)$, so that 

$$
X R_y(\theta) X) = X^2\cos(\theta/2) - iXYX\sin(\theta/2) = I\cos(\theta/2)+iY\sin(\theta/2) =\\
I\cos(-\theta/2)-iY\sin(-\theta/2) = R_y(-\theta)
$$

### Exercise 4.13

In [8]:
H*X*H

matrix([[ 1.,  0.],
        [ 0., -1.]])

In [11]:
np.round(H*Y*H)

matrix([[0.-0.j, 0.+1.j],
        [0.-1.j, 0.+0.j]])

In [12]:
H*Z*H

matrix([[0., 1.],
        [1., 0.]])

### Exercise 4.16

In [20]:
np.outer(H, I)

array([[ 0.70710678,  0.        ,  0.        ,  0.70710678],
       [ 0.70710678,  0.        ,  0.        ,  0.70710678],
       [ 0.70710678,  0.        ,  0.        ,  0.70710678],
       [-0.70710678, -0.        , -0.        , -0.70710678]])

In [21]:
np.outer(I,H)

array([[ 0.70710678,  0.70710678,  0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        , -0.        ],
       [ 0.70710678,  0.70710678,  0.70710678, -0.70710678]])